version: '3.3'

networks:
 proxy-net:
   external: true
      
services:
    reverse-proxy:
     image: traefik:latest
     command:
      --providers.docker
      --providers.docker.exposedbydefault=false
      --providers.docker.swarmmode=true
      --entryPoints.web.address=":80"
      --entryPoints.websecure.address=":443"
      --entryPoints.mysql.address=":3306"
      --accesslog
      --log.level=DEBUG
      --api=true
      --api.dashboard=true
     ports:
       - 80:80
       - 443:443
       - 8080:8080
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /var/cert:/certs/
       - /home/rootmessages/BPMspaceCloud/dockerswarm/management/traefik/config:/etc/traefik/
     deploy:
        mode: global
        placement:
          constraints:
            - node.role == manager
        labels:
          - traefik.enable=true
          - traefik.http.routers.traefikRouter.rule=Host(`traefik.bpmspace.net`)
          - traefik.http.routers.traefikRouter.tls=true
          - traefik.http.routers.traefikRouter.entrypoints=websecure
          - traefik.http.routers.traefikRouter.service=api@internal
          - traefik.http.routers.traefikRouter.middlewares=dshbrd-auth
          - traefik.http.middlewares.dshbrd-auth.basicauth.users=rootmessages:$$apr1$$G4tOTTMW$$limDBQWcCnVhwHEHkhAim1
          - traefik.http.services.justAdummyService.loadbalancer.server.port=1337
     networks:
       - proxy-net