version: '3.3'

networks:
 proxy-net:
   external: true
   
services:
  whoami:
    image: containous/whoami
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami.bpmspace.net`)
        - traefik.http.services.whoami-service.loadbalancer.server.port=80
    networks:
      - proxy-net   
