# ICO-ENV-DEV
version: '3.7'

networks:
 proxy-net:
   external: true
   
volumes:
  ICO-ENV-DEV-mariadb10:
  ICO-ENV-DEV-liam3-client:
  ICO-ENV-DEV-liam3-server:
  ICO-ENV-DEV-coms-server:
  ICO-ENV-DEV-coms-client2:
  ICO-ENV-DEV-sqms2-server:
  ICO-ENV-DEV-www-server:
  ICO-ENV-DEV-shop-server:

services:

  ICO-ENV-DEV-mariadb10:
    image: mariadb:10.4.8
    hostname: ICO-ENV-DEV-mariadb10
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    restart: always
    volumes:
    - ICO-ENV-DEV-mariadb10:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=bpmspace7603476
    - MYSQL_DATABASE=bpmspace_ico_shop_v1
    - MYSQL_USER=bpmspace_ico_shop_v1
    - MYSQL_PASSWORD=bpmspace7603476
    networks:
      - proxy-net 
    deploy:
      placement:
        constraints: [node.role == manager]

  ICO-ENV-DEV-phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: ICO-ENV-DEV-phpmyadmin-mariadb10
    depends_on:
    - ICO-ENV-DEV-mariadb10
    environment:
    - PMA_HOST=ICO-ENV-DEV-mariadb10
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=bpmspace7603476
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ICO-ENV-DEV-phpmyadmin-mariadb.rule=Host(`ICO-ENV-DEV-phpmyadmin-mariadb10.ico.bpmspace.net`)
        - traefik.http.services.ICO-ENV-DEV-phpmyadmin-mariadb-service.loadbalancer.server.port=80
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net 

  ICO-ENV-DEV-liam3-server:
    image: bpmspace/liam3:liam3_master-production_server_master
    hostname: ICO-ENV-DEV-liam3-server
    volumes:
    - ICO-ENV-DEV-liam3-server:/var/www/html
    - /mnt/gluster/gluster_bpmspacecloud/conf/ico-liam3_prms/dev/liam3_server_config.SECRET.inc.php:/var/www/html/config.SECRET.inc.php
    depends_on:
    - ICO-ENV-DEV-liam3-mariadb10
    environment:
    - DB_HOST=ICO-ENV-DEV-liam3-mariadb10
    - DB_PORT=3306
    - DB_NAME=bpmspace_liam3-v1
    - DB_USER=bpmspace_liam3-v1
    - DB_PASSWORD=bpmspace7603476
    - DB_ROOT_PASSWORD=bpmspace7603476
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ICO-ENV-DEV-liam3-server.rule=Host(`ICO-ENV-DEV-liam3-server.ico.bpmspace.net`)
        - traefik.http.services.ICO-ENV-DEV-liam3-server-service.loadbalancer.server.port=80
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net

  ICO-ENV-DEV-liam3-client:
    image: bpmspace/liam3_client:liam3_client_master-production_server_master
    hostname: ICO-ENV-DEV-liam3-client
    volumes:
    - ICO-ENV-DEV-liam3-client:/var/www/html
    - /mnt/gluster/gluster_bpmspacecloud/conf/ico-liam3_prms/dev/liam3_client_config.SECRET.inc.php:/var/www/html/inc/liam3_Client_api.secret.inc.php
    depends_on:
    - ICO-ENV-DEV-liam3-server
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ICO-ENV-DEV-liam3-client.rule=Host(`ICO-ENV-DEV-liam3-client.ico.bpmspace.net`)
        - traefik.http.services.ICO-ENV-DEV-liam3-client-service.loadbalancer.server.port=80
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net

  ICO-ENV-SHOP-DEV-server:
    image: bpmspace/ico-shop:ico-shop_master-production_server_master
    hostname: ICO-ENV-SHOP-DEV-server
    volumes:
    - ICO-ENV-DEV-shop-server:/var/www/html/
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ICO-ENV-SHOP-DEV-server.rule=Host(`ICO-ENV-SHOP-DEV-server.ico.bpmspace.net`)
        - traefik.http.services.ICO-ENV-SHOP-DEV-server-service.loadbalancer.server.port=80
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net
      
  ICO-ENV-DEV-mailhog:
    image: mailhog/mailhog
    hostname: ICO-ENV-DEV-mailhog
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ICO-ENV-DEV-mailhog.rule=Host(`ICO-ENV-DEV-mailhog.ico.bpmspace.net`)
        - traefik.http.services.ICO-ENV-DEV-mailhog-service.loadbalancer.server.port=8025
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net

  ICO-ENV-DEV-sftp:
    image: bpmspace/docker_bpmspace_base:atmoz_sftp
    hostname: ICO-ENV-DEV-sftp
    command: developer:pass:33
    depends_on:
    - ICO-ENV-DEV-liam3-server
    - ICO-ENV-DEV-liam3-client
    - ICO-ENV-SHOP-DEV-server
    ports:
        - "7373:22"
    volumes:
    - ICO-ENV-DEV-liam3-server:/home/developer/ICO-ENV-DEV-liam3-server
    - ICO-ENV-DEV-liam3-client:/home/developer/ICO-ENV-DEV-liam3-client
    - ICO-ENV-DEV-shop-server:/home/developer/ICO-ENV-DEV-shop-server
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-net
